# Site Settings
encoding: UTF-8
exclude:
  [
    '*.gem',
    '*.gemspec',
    'doc',
    'docs',
    'Gemfile',
    'Gemfile.lock',
    'node_modules',
    'Rakefile',
    'starter-kit',
    'yizeng.github.io',
    'vendor',
  ]
lang: en
permalink: /:year/:month/:day/:title/
theme: jekyll-theme-simple-texture

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ['apos', 'apos', 'quot', 'quot']
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://liujiayi1.netlify.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: LiuJiaYi’s Blog
description: 'Personal blog for LiuJiaYi, an undergraduate student in CUP, China.'
keywords: 'natural gas hydrate, molecular dynamics, optimization'
author:
  name: LiuJiaYi
  job_title: Undergraduate student
  location: Beijing, China
  email: 2016010775@student.cup.edu.cn
  social_links:
    - name: github
      url: https://github.com/LiuJiaYiCup/
    - name: Zhihu
      url: https://www.zhihu.com/people/zhua-zhua-81-64/activities/
home:
  section1:
  section2:
  section3:

disqus:
  shortname: yizeng
  public_key: ULZ0b9TFdfCUJSKQd4WCKv2v3u25YoG7YG8zXPewkWrT35lZ0Se9YnxLzoV6VM8W
google_tag_manager: 'GTM-P5NFP45'
addthis_public_id: ra-53819e27689934f9 # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
